[TEST]
ec2-test ansible_host=13.201.26.111 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

[UAT]
ec2-UAT ansible_host=13.126.90.162 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

[PROD]
ec2-prod ansible_host=65.2.186.21 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

