[TEST]
ec2-test ansible_host=13.233.247.113 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

[UAT]
ec2-UAT ansible_host=13.127.73.121 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

[PROD]
ec2-prod ansible_host=3.109.4.211 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

