[TEST]
ec2-test ansible_host=3.111.168.26 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

[UAT]
ec2-UAT ansible_host=13.233.237.170 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

[PROD]
ec2-prod ansible_host=13.232.94.22 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no' 

