- name: Deploy Flask Backend App
  hosts: "{{ target }}"
  become: yes

  vars:
    image_name: "{{ lookup('env', 'IMAGE_NAME') }}"   # passed from GitHub Actions
    container_name: flask-backend
    host_port: 80       # expose app to internet
    container_port: 5000

  tasks:
    - name: Ensure old container is stopped
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: docker.io
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"   # from GitHub Secrets
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Pull latest Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run container with new image
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:{{ container_port }}"
